on:
  push:
    paths:
      - atcodertwitterprofileupdater-backend/**
    branches:
      - master
name: Auto Deploy to AWS
jobs:
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        working-directory: atcodertwitterprofileupdater-backend
        run: |
          yarn global add aws-cdk
          yarn
          cd lambda
          for dir in ./*; do
            cd $dir
            yarn
            cd ..
          done
      - name: Deploy to AWS
        working-directory: atcodertwitterprofileupdater-backend
        run: $(yarn global bin)/cdk deploy --require-approval never
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
